source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'
use_frameworks!

target 'StrizhApp' do
    
    pod 'Alamofire', '~> 4.3'
    pod 'ObjectMapper', '~> 2.2'
    pod 'RealmSwift'
    pod 'AlamofireObjectMapper', '~> 4.0'
    pod 'AlamofireImage', '~> 3.1'
    pod 'BrightFutures'
    pod 'Bond', '~> 6.0'
    pod 'Socket.IO-Client-Swift'
    pod 'Firebase/Crash'
#    pod 'PhoneNumberKit', '~> 1.2'
    pod 'SHSPhoneComponent'
#    pod 'Mortar'
    pod 'NVActivityIndicatorView'
#    pod 'EmitterKit'
    pod 'GoogleMaps'
    pod 'DKImagePickerController'
    pod 'KDCircularProgress'
    pod 'Dip'
    pod 'Dip-UI'
    pod 'Flurry-iOS-SDK/FlurrySDK'
#    pod 'Gemini'
#    pod 'ActiveLabel'
#    pod 'TTTAttributedLabel'
#    pod 'RxSwift', '~> 3.0'
#    pod 'RxCocoa', '~> 3.0'
#    pod 'RxDataSources', '~> 1.0'
#    pod 'APNGKit', '~> 0.6'
end
